// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddEdgeArgs {
    pub workflow_id: String,
    pub from_node_uuid: String,
    pub from_output: String,
    pub to_node_uuid: String,
    pub to_input: String,
}

impl From<AddEdgeArgs> for super::Reducer {
    fn from(args: AddEdgeArgs) -> Self {
        Self::AddEdge {
            workflow_id: args.workflow_id,
            from_node_uuid: args.from_node_uuid,
            from_output: args.from_output,
            to_node_uuid: args.to_node_uuid,
            to_input: args.to_input,
}
}
}

impl __sdk::InModule for AddEdgeArgs {
    type Module = super::RemoteModule;
}

pub struct AddEdgeCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_edge`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_edge {
    /// Request that the remote module invoke the reducer `add_edge` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_edge`] callbacks.
    fn add_edge(&self, workflow_id: String,
from_node_uuid: String,
from_output: String,
to_node_uuid: String,
to_input: String,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_edge`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddEdgeCallbackId`] can be passed to [`Self::remove_on_add_edge`]
    /// to cancel the callback.
    fn on_add_edge(&self, callback: impl FnMut(&super::ReducerEventContext, &String, &String, &String, &String, &String, ) + Send + 'static) -> AddEdgeCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_edge`],
    /// causing it not to run in the future.
    fn remove_on_add_edge(&self, callback: AddEdgeCallbackId);
}

impl add_edge for super::RemoteReducers {
    fn add_edge(&self, workflow_id: String,
from_node_uuid: String,
from_output: String,
to_node_uuid: String,
to_input: String,
) -> __sdk::Result<()> {
        self.imp.call_reducer("add_edge", AddEdgeArgs { workflow_id, from_node_uuid, from_output, to_node_uuid, to_input,  })
    }
    fn on_add_edge(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, &String, &String, &String, ) + Send + 'static,
    ) -> AddEdgeCallbackId {
        AddEdgeCallbackId(self.imp.on_reducer(
            "add_edge",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::AddEdge {
                            workflow_id, from_node_uuid, from_output, to_node_uuid, to_input, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, workflow_id, from_node_uuid, from_output, to_node_uuid, to_input, )
            }),
        ))
    }
    fn remove_on_add_edge(&self, callback: AddEdgeCallbackId) {
        self.imp.remove_on_reducer("add_edge", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_edge`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_edge {
    /// Set the call-reducer flags for the reducer `add_edge` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_edge(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_edge for super::SetReducerFlags {
    fn add_edge(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_edge", flags);
    }
}

