// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddNodeArgs {
    pub workflow_id: String,
    pub node_uuid: String,
    pub node_type: String,
    pub name: String,
    pub position_x: f32,
    pub position_y: f32,
    pub config_json: String,
}

impl From<AddNodeArgs> for super::Reducer {
    fn from(args: AddNodeArgs) -> Self {
        Self::AddNode {
            workflow_id: args.workflow_id,
            node_uuid: args.node_uuid,
            node_type: args.node_type,
            name: args.name,
            position_x: args.position_x,
            position_y: args.position_y,
            config_json: args.config_json,
}
}
}

impl __sdk::InModule for AddNodeArgs {
    type Module = super::RemoteModule;
}

pub struct AddNodeCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_node`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_node {
    /// Request that the remote module invoke the reducer `add_node` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_node`] callbacks.
    fn add_node(&self, workflow_id: String,
node_uuid: String,
node_type: String,
name: String,
position_x: f32,
position_y: f32,
config_json: String,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_node`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddNodeCallbackId`] can be passed to [`Self::remove_on_add_node`]
    /// to cancel the callback.
    fn on_add_node(&self, callback: impl FnMut(&super::ReducerEventContext, &String, &String, &String, &String, &f32, &f32, &String, ) + Send + 'static) -> AddNodeCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_node`],
    /// causing it not to run in the future.
    fn remove_on_add_node(&self, callback: AddNodeCallbackId);
}

impl add_node for super::RemoteReducers {
    fn add_node(&self, workflow_id: String,
node_uuid: String,
node_type: String,
name: String,
position_x: f32,
position_y: f32,
config_json: String,
) -> __sdk::Result<()> {
        self.imp.call_reducer("add_node", AddNodeArgs { workflow_id, node_uuid, node_type, name, position_x, position_y, config_json,  })
    }
    fn on_add_node(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, &String, &String, &f32, &f32, &String, ) + Send + 'static,
    ) -> AddNodeCallbackId {
        AddNodeCallbackId(self.imp.on_reducer(
            "add_node",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::AddNode {
                            workflow_id, node_uuid, node_type, name, position_x, position_y, config_json, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, workflow_id, node_uuid, node_type, name, position_x, position_y, config_json, )
            }),
        ))
    }
    fn remove_on_add_node(&self, callback: AddNodeCallbackId) {
        self.imp.remove_on_reducer("add_node", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_node`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_node {
    /// Set the call-reducer flags for the reducer `add_node` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_node(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_node for super::SetReducerFlags {
    fn add_node(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_node", flags);
    }
}

