// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClearSelectionArgs {}

impl From<ClearSelectionArgs> for super::Reducer {
    fn from(args: ClearSelectionArgs) -> Self {
        Self::ClearSelection
    }
}

impl __sdk::InModule for ClearSelectionArgs {
    type Module = super::RemoteModule;
}

pub struct ClearSelectionCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `clear_selection`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait clear_selection {
    /// Request that the remote module invoke the reducer `clear_selection` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_clear_selection`] callbacks.
    fn clear_selection(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `clear_selection`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ClearSelectionCallbackId`] can be passed to [`Self::remove_on_clear_selection`]
    /// to cancel the callback.
    fn on_clear_selection(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ClearSelectionCallbackId;
    /// Cancel a callback previously registered by [`Self::on_clear_selection`],
    /// causing it not to run in the future.
    fn remove_on_clear_selection(&self, callback: ClearSelectionCallbackId);
}

impl clear_selection for super::RemoteReducers {
    fn clear_selection(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("clear_selection", ClearSelectionArgs {})
    }
    fn on_clear_selection(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ClearSelectionCallbackId {
        ClearSelectionCallbackId(self.imp.on_reducer(
            "clear_selection",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ClearSelection {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_clear_selection(&self, callback: ClearSelectionCallbackId) {
        self.imp.remove_on_reducer("clear_selection", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `clear_selection`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_clear_selection {
    /// Set the call-reducer flags for the reducer `clear_selection` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn clear_selection(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_clear_selection for super::SetReducerFlags {
    fn clear_selection(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("clear_selection", flags);
    }
}
