// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateWorkflowArgs {
    pub id: String,
    pub name: String,
}

impl From<CreateWorkflowArgs> for super::Reducer {
    fn from(args: CreateWorkflowArgs) -> Self {
        Self::CreateWorkflow {
            id: args.id,
            name: args.name,
        }
    }
}

impl __sdk::InModule for CreateWorkflowArgs {
    type Module = super::RemoteModule;
}

pub struct CreateWorkflowCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_workflow`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_workflow {
    /// Request that the remote module invoke the reducer `create_workflow` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_workflow`] callbacks.
    fn create_workflow(&self, id: String, name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_workflow`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateWorkflowCallbackId`] can be passed to [`Self::remove_on_create_workflow`]
    /// to cancel the callback.
    fn on_create_workflow(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> CreateWorkflowCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_workflow`],
    /// causing it not to run in the future.
    fn remove_on_create_workflow(&self, callback: CreateWorkflowCallbackId);
}

impl create_workflow for super::RemoteReducers {
    fn create_workflow(&self, id: String, name: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("create_workflow", CreateWorkflowArgs { id, name })
    }
    fn on_create_workflow(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> CreateWorkflowCallbackId {
        CreateWorkflowCallbackId(self.imp.on_reducer(
            "create_workflow",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CreateWorkflow { id, name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id, name)
            }),
        ))
    }
    fn remove_on_create_workflow(&self, callback: CreateWorkflowCallbackId) {
        self.imp.remove_on_reducer("create_workflow", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_workflow`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_workflow {
    /// Set the call-reducer flags for the reducer `create_workflow` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_workflow(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_workflow for super::SetReducerFlags {
    fn create_workflow(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_workflow", flags);
    }
}
