// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteNodeArgs {
    pub workflow_id: String,
    pub node_uuid: String,
}

impl From<DeleteNodeArgs> for super::Reducer {
    fn from(args: DeleteNodeArgs) -> Self {
        Self::DeleteNode {
            workflow_id: args.workflow_id,
            node_uuid: args.node_uuid,
        }
    }
}

impl __sdk::InModule for DeleteNodeArgs {
    type Module = super::RemoteModule;
}

pub struct DeleteNodeCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_node`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_node {
    /// Request that the remote module invoke the reducer `delete_node` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_delete_node`] callbacks.
    fn delete_node(&self, workflow_id: String, node_uuid: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `delete_node`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DeleteNodeCallbackId`] can be passed to [`Self::remove_on_delete_node`]
    /// to cancel the callback.
    fn on_delete_node(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> DeleteNodeCallbackId;
    /// Cancel a callback previously registered by [`Self::on_delete_node`],
    /// causing it not to run in the future.
    fn remove_on_delete_node(&self, callback: DeleteNodeCallbackId);
}

impl delete_node for super::RemoteReducers {
    fn delete_node(&self, workflow_id: String, node_uuid: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "delete_node",
            DeleteNodeArgs {
                workflow_id,
                node_uuid,
            },
        )
    }
    fn on_delete_node(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> DeleteNodeCallbackId {
        DeleteNodeCallbackId(self.imp.on_reducer(
            "delete_node",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::DeleteNode {
                                    workflow_id,
                                    node_uuid,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, workflow_id, node_uuid)
            }),
        ))
    }
    fn remove_on_delete_node(&self, callback: DeleteNodeCallbackId) {
        self.imp.remove_on_reducer("delete_node", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_node`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_delete_node {
    /// Set the call-reducer flags for the reducer `delete_node` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn delete_node(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_node for super::SetReducerFlags {
    fn delete_node(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("delete_node", flags);
    }
}
