// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteWorkflowArgs {
    pub workflow_id: String,
}

impl From<DeleteWorkflowArgs> for super::Reducer {
    fn from(args: DeleteWorkflowArgs) -> Self {
        Self::DeleteWorkflow {
            workflow_id: args.workflow_id,
}
}
}

impl __sdk::InModule for DeleteWorkflowArgs {
    type Module = super::RemoteModule;
}

pub struct DeleteWorkflowCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_workflow`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_workflow {
    /// Request that the remote module invoke the reducer `delete_workflow` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_delete_workflow`] callbacks.
    fn delete_workflow(&self, workflow_id: String,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `delete_workflow`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DeleteWorkflowCallbackId`] can be passed to [`Self::remove_on_delete_workflow`]
    /// to cancel the callback.
    fn on_delete_workflow(&self, callback: impl FnMut(&super::ReducerEventContext, &String, ) + Send + 'static) -> DeleteWorkflowCallbackId;
    /// Cancel a callback previously registered by [`Self::on_delete_workflow`],
    /// causing it not to run in the future.
    fn remove_on_delete_workflow(&self, callback: DeleteWorkflowCallbackId);
}

impl delete_workflow for super::RemoteReducers {
    fn delete_workflow(&self, workflow_id: String,
) -> __sdk::Result<()> {
        self.imp.call_reducer("delete_workflow", DeleteWorkflowArgs { workflow_id,  })
    }
    fn on_delete_workflow(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, ) + Send + 'static,
    ) -> DeleteWorkflowCallbackId {
        DeleteWorkflowCallbackId(self.imp.on_reducer(
            "delete_workflow",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::DeleteWorkflow {
                            workflow_id, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, workflow_id, )
            }),
        ))
    }
    fn remove_on_delete_workflow(&self, callback: DeleteWorkflowCallbackId) {
        self.imp.remove_on_reducer("delete_workflow", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_workflow`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_delete_workflow {
    /// Set the call-reducer flags for the reducer `delete_workflow` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn delete_workflow(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_workflow for super::SetReducerFlags {
    fn delete_workflow(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("delete_workflow", flags);
    }
}

