// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DragState {
    pub user_identity: __sdk::Identity,
    pub workflow_id: String,
    pub drag_type: String,
    pub node_uuids: String,
    pub from_pin: String,
    pub start_x: f32,
    pub start_y: f32,
    pub current_x: f32,
    pub current_y: f32,
    pub last_updated: __sdk::Timestamp,
}

impl __sdk::InModule for DragState {
    type Module = super::RemoteModule;
}
