// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::drag_state_type::DragState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `drag_state`.
///
/// Obtain a handle from the [`DragStateTableAccess::drag_state`] method on [`super::RemoteTables`],
/// like `ctx.db.drag_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.drag_state().on_insert(...)`.
pub struct DragStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<DragState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `drag_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DragStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DragStateTableHandle`], which mediates access to the table `drag_state`.
    fn drag_state(&self) -> DragStateTableHandle<'_>;
}

impl DragStateTableAccess for super::RemoteTables {
    fn drag_state(&self) -> DragStateTableHandle<'_> {
        DragStateTableHandle {
            imp: self.imp.get_table::<DragState>("drag_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DragStateInsertCallbackId(__sdk::CallbackId);
pub struct DragStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DragStateTableHandle<'ctx> {
    type Row = DragState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DragState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DragStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DragStateInsertCallbackId {
        DragStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DragStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DragStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DragStateDeleteCallbackId {
        DragStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DragStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DragState>("drag_state");
    _table.add_unique_constraint::<__sdk::Identity>("user_identity", |row| &row.user_identity);
}
pub struct DragStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DragStateTableHandle<'ctx> {
    type UpdateCallbackId = DragStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DragStateUpdateCallbackId {
        DragStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DragStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<DragState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DragState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `user_identity` unique index on the table `drag_state`,
/// which allows point queries on the field of the same name
/// via the [`DragStateUserIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.drag_state().user_identity().find(...)`.
pub struct DragStateUserIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DragState, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DragStateTableHandle<'ctx> {
    /// Get a handle on the `user_identity` unique index on the table `drag_state`.
    pub fn user_identity(&self) -> DragStateUserIdentityUnique<'ctx> {
        DragStateUserIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("user_identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DragStateUserIdentityUnique<'ctx> {
    /// Find the subscribed row whose `user_identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<DragState> {
        self.imp.find(col_val)
    }
}
