// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EndDragArgs {}

impl From<EndDragArgs> for super::Reducer {
    fn from(args: EndDragArgs) -> Self {
        Self::EndDrag
    }
}

impl __sdk::InModule for EndDragArgs {
    type Module = super::RemoteModule;
}

pub struct EndDragCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `end_drag`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait end_drag {
    /// Request that the remote module invoke the reducer `end_drag` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_end_drag`] callbacks.
    fn end_drag(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `end_drag`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`EndDragCallbackId`] can be passed to [`Self::remove_on_end_drag`]
    /// to cancel the callback.
    fn on_end_drag(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> EndDragCallbackId;
    /// Cancel a callback previously registered by [`Self::on_end_drag`],
    /// causing it not to run in the future.
    fn remove_on_end_drag(&self, callback: EndDragCallbackId);
}

impl end_drag for super::RemoteReducers {
    fn end_drag(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("end_drag", EndDragArgs {})
    }
    fn on_end_drag(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> EndDragCallbackId {
        EndDragCallbackId(self.imp.on_reducer(
            "end_drag",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::EndDrag {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_end_drag(&self, callback: EndDragCallbackId) {
        self.imp.remove_on_reducer("end_drag", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `end_drag`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_end_drag {
    /// Set the call-reducer flags for the reducer `end_drag` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn end_drag(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_end_drag for super::SetReducerFlags {
    fn end_drag(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("end_drag", flags);
    }
}
