// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ExecutionLog {
    pub id: u64,
    pub workflow_id: String,
    pub started_at: __sdk::Timestamp,
    pub finished_at: Option::<__sdk::Timestamp>,
    pub status: String,
    pub trigger_type: String,
    pub error_message: Option::<String>,
    pub triggered_by: __sdk::Identity,
}


impl __sdk::InModule for ExecutionLog {
    type Module = super::RemoteModule;
}

