// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::execution_log_type::ExecutionLog;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `execution_log`.
///
/// Obtain a handle from the [`ExecutionLogTableAccess::execution_log`] method on [`super::RemoteTables`],
/// like `ctx.db.execution_log()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.execution_log().on_insert(...)`.
pub struct ExecutionLogTableHandle<'ctx> {
    imp: __sdk::TableHandle<ExecutionLog>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `execution_log`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ExecutionLogTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ExecutionLogTableHandle`], which mediates access to the table `execution_log`.
    fn execution_log(&self) -> ExecutionLogTableHandle<'_>;
}

impl ExecutionLogTableAccess for super::RemoteTables {
    fn execution_log(&self) -> ExecutionLogTableHandle<'_> {
        ExecutionLogTableHandle {
            imp: self.imp.get_table::<ExecutionLog>("execution_log"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ExecutionLogInsertCallbackId(__sdk::CallbackId);
pub struct ExecutionLogDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ExecutionLogTableHandle<'ctx> {
    type Row = ExecutionLog;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ExecutionLog> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ExecutionLogInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ExecutionLogInsertCallbackId {
        ExecutionLogInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ExecutionLogInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ExecutionLogDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ExecutionLogDeleteCallbackId {
        ExecutionLogDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ExecutionLogDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ExecutionLog>("execution_log");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct ExecutionLogUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ExecutionLogTableHandle<'ctx> {
    type UpdateCallbackId = ExecutionLogUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ExecutionLogUpdateCallbackId {
        ExecutionLogUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ExecutionLogUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ExecutionLog>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ExecutionLog>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `execution_log`,
/// which allows point queries on the field of the same name
/// via the [`ExecutionLogIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.execution_log().id().find(...)`.
pub struct ExecutionLogIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ExecutionLog, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ExecutionLogTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `execution_log`.
    pub fn id(&self) -> ExecutionLogIdUnique<'ctx> {
        ExecutionLogIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ExecutionLogIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ExecutionLog> {
        self.imp.find(col_val)
    }
}
