// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct JoinWorkflowArgs {
    pub workflow_id: String,
    pub nickname: String,
    pub cursor_color: u32,
}

impl From<JoinWorkflowArgs> for super::Reducer {
    fn from(args: JoinWorkflowArgs) -> Self {
        Self::JoinWorkflow {
            workflow_id: args.workflow_id,
            nickname: args.nickname,
            cursor_color: args.cursor_color,
        }
    }
}

impl __sdk::InModule for JoinWorkflowArgs {
    type Module = super::RemoteModule;
}

pub struct JoinWorkflowCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `join_workflow`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait join_workflow {
    /// Request that the remote module invoke the reducer `join_workflow` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_join_workflow`] callbacks.
    fn join_workflow(
        &self,
        workflow_id: String,
        nickname: String,
        cursor_color: u32,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `join_workflow`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`JoinWorkflowCallbackId`] can be passed to [`Self::remove_on_join_workflow`]
    /// to cancel the callback.
    fn on_join_workflow(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String, &u32) + Send + 'static,
    ) -> JoinWorkflowCallbackId;
    /// Cancel a callback previously registered by [`Self::on_join_workflow`],
    /// causing it not to run in the future.
    fn remove_on_join_workflow(&self, callback: JoinWorkflowCallbackId);
}

impl join_workflow for super::RemoteReducers {
    fn join_workflow(
        &self,
        workflow_id: String,
        nickname: String,
        cursor_color: u32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "join_workflow",
            JoinWorkflowArgs {
                workflow_id,
                nickname,
                cursor_color,
            },
        )
    }
    fn on_join_workflow(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, &u32) + Send + 'static,
    ) -> JoinWorkflowCallbackId {
        JoinWorkflowCallbackId(self.imp.on_reducer(
            "join_workflow",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::JoinWorkflow {
                                    workflow_id,
                                    nickname,
                                    cursor_color,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, workflow_id, nickname, cursor_color)
            }),
        ))
    }
    fn remove_on_join_workflow(&self, callback: JoinWorkflowCallbackId) {
        self.imp.remove_on_reducer("join_workflow", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `join_workflow`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_join_workflow {
    /// Set the call-reducer flags for the reducer `join_workflow` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn join_workflow(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_join_workflow for super::SetReducerFlags {
    fn join_workflow(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("join_workflow", flags);
    }
}
