// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveNodeArgs {
    pub workflow_id: String,
    pub node_uuid: String,
    pub position_x: f32,
    pub position_y: f32,
}

impl From<MoveNodeArgs> for super::Reducer {
    fn from(args: MoveNodeArgs) -> Self {
        Self::MoveNode {
            workflow_id: args.workflow_id,
            node_uuid: args.node_uuid,
            position_x: args.position_x,
            position_y: args.position_y,
}
}
}

impl __sdk::InModule for MoveNodeArgs {
    type Module = super::RemoteModule;
}

pub struct MoveNodeCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_node`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_node {
    /// Request that the remote module invoke the reducer `move_node` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_move_node`] callbacks.
    fn move_node(&self, workflow_id: String,
node_uuid: String,
position_x: f32,
position_y: f32,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `move_node`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MoveNodeCallbackId`] can be passed to [`Self::remove_on_move_node`]
    /// to cancel the callback.
    fn on_move_node(&self, callback: impl FnMut(&super::ReducerEventContext, &String, &String, &f32, &f32, ) + Send + 'static) -> MoveNodeCallbackId;
    /// Cancel a callback previously registered by [`Self::on_move_node`],
    /// causing it not to run in the future.
    fn remove_on_move_node(&self, callback: MoveNodeCallbackId);
}

impl move_node for super::RemoteReducers {
    fn move_node(&self, workflow_id: String,
node_uuid: String,
position_x: f32,
position_y: f32,
) -> __sdk::Result<()> {
        self.imp.call_reducer("move_node", MoveNodeArgs { workflow_id, node_uuid, position_x, position_y,  })
    }
    fn on_move_node(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, &f32, &f32, ) + Send + 'static,
    ) -> MoveNodeCallbackId {
        MoveNodeCallbackId(self.imp.on_reducer(
            "move_node",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::MoveNode {
                            workflow_id, node_uuid, position_x, position_y, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, workflow_id, node_uuid, position_x, position_y, )
            }),
        ))
    }
    fn remove_on_move_node(&self, callback: MoveNodeCallbackId) {
        self.imp.remove_on_reducer("move_node", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `move_node`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_move_node {
    /// Set the call-reducer flags for the reducer `move_node` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn move_node(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_move_node for super::SetReducerFlags {
    fn move_node(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("move_node", flags);
    }
}

