// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ShareWorkflowArgs {
    pub workflow_id: String,
    pub is_shared: bool,
}

impl From<ShareWorkflowArgs> for super::Reducer {
    fn from(args: ShareWorkflowArgs) -> Self {
        Self::ShareWorkflow {
            workflow_id: args.workflow_id,
            is_shared: args.is_shared,
        }
    }
}

impl __sdk::InModule for ShareWorkflowArgs {
    type Module = super::RemoteModule;
}

pub struct ShareWorkflowCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `share_workflow`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait share_workflow {
    /// Request that the remote module invoke the reducer `share_workflow` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_share_workflow`] callbacks.
    fn share_workflow(&self, workflow_id: String, is_shared: bool) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `share_workflow`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ShareWorkflowCallbackId`] can be passed to [`Self::remove_on_share_workflow`]
    /// to cancel the callback.
    fn on_share_workflow(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &bool) + Send + 'static,
    ) -> ShareWorkflowCallbackId;
    /// Cancel a callback previously registered by [`Self::on_share_workflow`],
    /// causing it not to run in the future.
    fn remove_on_share_workflow(&self, callback: ShareWorkflowCallbackId);
}

impl share_workflow for super::RemoteReducers {
    fn share_workflow(&self, workflow_id: String, is_shared: bool) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "share_workflow",
            ShareWorkflowArgs {
                workflow_id,
                is_shared,
            },
        )
    }
    fn on_share_workflow(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &bool) + Send + 'static,
    ) -> ShareWorkflowCallbackId {
        ShareWorkflowCallbackId(self.imp.on_reducer(
            "share_workflow",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::ShareWorkflow {
                                    workflow_id,
                                    is_shared,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, workflow_id, is_shared)
            }),
        ))
    }
    fn remove_on_share_workflow(&self, callback: ShareWorkflowCallbackId) {
        self.imp.remove_on_reducer("share_workflow", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `share_workflow`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_share_workflow {
    /// Set the call-reducer flags for the reducer `share_workflow` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn share_workflow(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_share_workflow for super::SetReducerFlags {
    fn share_workflow(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("share_workflow", flags);
    }
}
