// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StartExecutionArgs {
    pub workflow_id: String,
    pub trigger_type: String,
}

impl From<StartExecutionArgs> for super::Reducer {
    fn from(args: StartExecutionArgs) -> Self {
        Self::StartExecution {
            workflow_id: args.workflow_id,
            trigger_type: args.trigger_type,
        }
    }
}

impl __sdk::InModule for StartExecutionArgs {
    type Module = super::RemoteModule;
}

pub struct StartExecutionCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `start_execution`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait start_execution {
    /// Request that the remote module invoke the reducer `start_execution` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_start_execution`] callbacks.
    fn start_execution(&self, workflow_id: String, trigger_type: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `start_execution`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`StartExecutionCallbackId`] can be passed to [`Self::remove_on_start_execution`]
    /// to cancel the callback.
    fn on_start_execution(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> StartExecutionCallbackId;
    /// Cancel a callback previously registered by [`Self::on_start_execution`],
    /// causing it not to run in the future.
    fn remove_on_start_execution(&self, callback: StartExecutionCallbackId);
}

impl start_execution for super::RemoteReducers {
    fn start_execution(&self, workflow_id: String, trigger_type: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "start_execution",
            StartExecutionArgs {
                workflow_id,
                trigger_type,
            },
        )
    }
    fn on_start_execution(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> StartExecutionCallbackId {
        StartExecutionCallbackId(self.imp.on_reducer(
            "start_execution",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::StartExecution {
                                    workflow_id,
                                    trigger_type,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, workflow_id, trigger_type)
            }),
        ))
    }
    fn remove_on_start_execution(&self, callback: StartExecutionCallbackId) {
        self.imp.remove_on_reducer("start_execution", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `start_execution`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_start_execution {
    /// Set the call-reducer flags for the reducer `start_execution` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn start_execution(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_start_execution for super::SetReducerFlags {
    fn start_execution(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("start_execution", flags);
    }
}
