// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StartDragArgs {
    pub workflow_id: String,
    pub drag_type: String,
    pub node_uuids: String,
    pub from_pin: String,
    pub x: f32,
    pub y: f32,
}

impl From<StartDragArgs> for super::Reducer {
    fn from(args: StartDragArgs) -> Self {
        Self::StartDrag {
            workflow_id: args.workflow_id,
            drag_type: args.drag_type,
            node_uuids: args.node_uuids,
            from_pin: args.from_pin,
            x: args.x,
            y: args.y,
        }
    }
}

impl __sdk::InModule for StartDragArgs {
    type Module = super::RemoteModule;
}

pub struct StartDragCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `start_drag`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait start_drag {
    /// Request that the remote module invoke the reducer `start_drag` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_start_drag`] callbacks.
    fn start_drag(
        &self,
        workflow_id: String,
        drag_type: String,
        node_uuids: String,
        from_pin: String,
        x: f32,
        y: f32,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `start_drag`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`StartDragCallbackId`] can be passed to [`Self::remove_on_start_drag`]
    /// to cancel the callback.
    fn on_start_drag(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String, &String, &String, &f32, &f32)
            + Send
            + 'static,
    ) -> StartDragCallbackId;
    /// Cancel a callback previously registered by [`Self::on_start_drag`],
    /// causing it not to run in the future.
    fn remove_on_start_drag(&self, callback: StartDragCallbackId);
}

impl start_drag for super::RemoteReducers {
    fn start_drag(
        &self,
        workflow_id: String,
        drag_type: String,
        node_uuids: String,
        from_pin: String,
        x: f32,
        y: f32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "start_drag",
            StartDragArgs {
                workflow_id,
                drag_type,
                node_uuids,
                from_pin,
                x,
                y,
            },
        )
    }
    fn on_start_drag(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, &String, &String, &f32, &f32)
            + Send
            + 'static,
    ) -> StartDragCallbackId {
        StartDragCallbackId(self.imp.on_reducer(
            "start_drag",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::StartDrag {
                                    workflow_id,
                                    drag_type,
                                    node_uuids,
                                    from_pin,
                                    x,
                                    y,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, workflow_id, drag_type, node_uuids, from_pin, x, y)
            }),
        ))
    }
    fn remove_on_start_drag(&self, callback: StartDragCallbackId) {
        self.imp.remove_on_reducer("start_drag", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `start_drag`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_start_drag {
    /// Set the call-reducer flags for the reducer `start_drag` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn start_drag(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_start_drag for super::SetReducerFlags {
    fn start_drag(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("start_drag", flags);
    }
}
