// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ToggleNodeDisabledArgs {
    pub workflow_id: String,
    pub node_uuid: String,
}

impl From<ToggleNodeDisabledArgs> for super::Reducer {
    fn from(args: ToggleNodeDisabledArgs) -> Self {
        Self::ToggleNodeDisabled {
            workflow_id: args.workflow_id,
            node_uuid: args.node_uuid,
        }
    }
}

impl __sdk::InModule for ToggleNodeDisabledArgs {
    type Module = super::RemoteModule;
}

pub struct ToggleNodeDisabledCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `toggle_node_disabled`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait toggle_node_disabled {
    /// Request that the remote module invoke the reducer `toggle_node_disabled` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_toggle_node_disabled`] callbacks.
    fn toggle_node_disabled(&self, workflow_id: String, node_uuid: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `toggle_node_disabled`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ToggleNodeDisabledCallbackId`] can be passed to [`Self::remove_on_toggle_node_disabled`]
    /// to cancel the callback.
    fn on_toggle_node_disabled(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> ToggleNodeDisabledCallbackId;
    /// Cancel a callback previously registered by [`Self::on_toggle_node_disabled`],
    /// causing it not to run in the future.
    fn remove_on_toggle_node_disabled(&self, callback: ToggleNodeDisabledCallbackId);
}

impl toggle_node_disabled for super::RemoteReducers {
    fn toggle_node_disabled(&self, workflow_id: String, node_uuid: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "toggle_node_disabled",
            ToggleNodeDisabledArgs {
                workflow_id,
                node_uuid,
            },
        )
    }
    fn on_toggle_node_disabled(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> ToggleNodeDisabledCallbackId {
        ToggleNodeDisabledCallbackId(self.imp.on_reducer(
            "toggle_node_disabled",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::ToggleNodeDisabled {
                                    workflow_id,
                                    node_uuid,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, workflow_id, node_uuid)
            }),
        ))
    }
    fn remove_on_toggle_node_disabled(&self, callback: ToggleNodeDisabledCallbackId) {
        self.imp
            .remove_on_reducer("toggle_node_disabled", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `toggle_node_disabled`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_toggle_node_disabled {
    /// Set the call-reducer flags for the reducer `toggle_node_disabled` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn toggle_node_disabled(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_toggle_node_disabled for super::SetReducerFlags {
    fn toggle_node_disabled(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("toggle_node_disabled", flags);
    }
}
