// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateNicknameArgs {
    pub nickname: String,
}

impl From<UpdateNicknameArgs> for super::Reducer {
    fn from(args: UpdateNicknameArgs) -> Self {
        Self::UpdateNickname {
            nickname: args.nickname,
}
}
}

impl __sdk::InModule for UpdateNicknameArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateNicknameCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_nickname`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_nickname {
    /// Request that the remote module invoke the reducer `update_nickname` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_nickname`] callbacks.
    fn update_nickname(&self, nickname: String,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_nickname`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateNicknameCallbackId`] can be passed to [`Self::remove_on_update_nickname`]
    /// to cancel the callback.
    fn on_update_nickname(&self, callback: impl FnMut(&super::ReducerEventContext, &String, ) + Send + 'static) -> UpdateNicknameCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_nickname`],
    /// causing it not to run in the future.
    fn remove_on_update_nickname(&self, callback: UpdateNicknameCallbackId);
}

impl update_nickname for super::RemoteReducers {
    fn update_nickname(&self, nickname: String,
) -> __sdk::Result<()> {
        self.imp.call_reducer("update_nickname", UpdateNicknameArgs { nickname,  })
    }
    fn on_update_nickname(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, ) + Send + 'static,
    ) -> UpdateNicknameCallbackId {
        UpdateNicknameCallbackId(self.imp.on_reducer(
            "update_nickname",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::UpdateNickname {
                            nickname, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, nickname, )
            }),
        ))
    }
    fn remove_on_update_nickname(&self, callback: UpdateNicknameCallbackId) {
        self.imp.remove_on_reducer("update_nickname", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_nickname`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_nickname {
    /// Set the call-reducer flags for the reducer `update_nickname` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_nickname(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_nickname for super::SetReducerFlags {
    fn update_nickname(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_nickname", flags);
    }
}

