// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateSelectionArgs {
    pub workflow_id: String,
    pub node_uuids: String,
}

impl From<UpdateSelectionArgs> for super::Reducer {
    fn from(args: UpdateSelectionArgs) -> Self {
        Self::UpdateSelection {
            workflow_id: args.workflow_id,
            node_uuids: args.node_uuids,
        }
    }
}

impl __sdk::InModule for UpdateSelectionArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateSelectionCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_selection`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_selection {
    /// Request that the remote module invoke the reducer `update_selection` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_selection`] callbacks.
    fn update_selection(&self, workflow_id: String, node_uuids: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_selection`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateSelectionCallbackId`] can be passed to [`Self::remove_on_update_selection`]
    /// to cancel the callback.
    fn on_update_selection(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> UpdateSelectionCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_selection`],
    /// causing it not to run in the future.
    fn remove_on_update_selection(&self, callback: UpdateSelectionCallbackId);
}

impl update_selection for super::RemoteReducers {
    fn update_selection(&self, workflow_id: String, node_uuids: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "update_selection",
            UpdateSelectionArgs {
                workflow_id,
                node_uuids,
            },
        )
    }
    fn on_update_selection(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> UpdateSelectionCallbackId {
        UpdateSelectionCallbackId(self.imp.on_reducer(
            "update_selection",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::UpdateSelection {
                                    workflow_id,
                                    node_uuids,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, workflow_id, node_uuids)
            }),
        ))
    }
    fn remove_on_update_selection(&self, callback: UpdateSelectionCallbackId) {
        self.imp.remove_on_reducer("update_selection", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_selection`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_selection {
    /// Set the call-reducer flags for the reducer `update_selection` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_selection(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_selection for super::SetReducerFlags {
    fn update_selection(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_selection", flags);
    }
}
