// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateDragArgs {
    pub x: f32,
    pub y: f32,
}

impl From<UpdateDragArgs> for super::Reducer {
    fn from(args: UpdateDragArgs) -> Self {
        Self::UpdateDrag {
            x: args.x,
            y: args.y,
        }
    }
}

impl __sdk::InModule for UpdateDragArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateDragCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_drag`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_drag {
    /// Request that the remote module invoke the reducer `update_drag` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_drag`] callbacks.
    fn update_drag(&self, x: f32, y: f32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_drag`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateDragCallbackId`] can be passed to [`Self::remove_on_update_drag`]
    /// to cancel the callback.
    fn on_update_drag(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &f32, &f32) + Send + 'static,
    ) -> UpdateDragCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_drag`],
    /// causing it not to run in the future.
    fn remove_on_update_drag(&self, callback: UpdateDragCallbackId);
}

impl update_drag for super::RemoteReducers {
    fn update_drag(&self, x: f32, y: f32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("update_drag", UpdateDragArgs { x, y })
    }
    fn on_update_drag(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &f32, &f32) + Send + 'static,
    ) -> UpdateDragCallbackId {
        UpdateDragCallbackId(self.imp.on_reducer(
            "update_drag",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdateDrag { x, y },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, x, y)
            }),
        ))
    }
    fn remove_on_update_drag(&self, callback: UpdateDragCallbackId) {
        self.imp.remove_on_reducer("update_drag", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_drag`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_drag {
    /// Set the call-reducer flags for the reducer `update_drag` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_drag(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_drag for super::SetReducerFlags {
    fn update_drag(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_drag", flags);
    }
}
