// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_presence_type::UserPresence;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_presence`.
///
/// Obtain a handle from the [`UserPresenceTableAccess::user_presence`] method on [`super::RemoteTables`],
/// like `ctx.db.user_presence()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_presence().on_insert(...)`.
pub struct UserPresenceTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserPresence>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_presence`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserPresenceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserPresenceTableHandle`], which mediates access to the table `user_presence`.
    fn user_presence(&self) -> UserPresenceTableHandle<'_>;
}

impl UserPresenceTableAccess for super::RemoteTables {
    fn user_presence(&self) -> UserPresenceTableHandle<'_> {
        UserPresenceTableHandle {
            imp: self.imp.get_table::<UserPresence>("user_presence"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserPresenceInsertCallbackId(__sdk::CallbackId);
pub struct UserPresenceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserPresenceTableHandle<'ctx> {
    type Row = UserPresence;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserPresence> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserPresenceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserPresenceInsertCallbackId {
        UserPresenceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserPresenceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserPresenceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserPresenceDeleteCallbackId {
        UserPresenceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserPresenceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserPresence>("user_presence");
    _table.add_unique_constraint::<__sdk::Identity>("user_identity", |row| &row.user_identity);
}
pub struct UserPresenceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserPresenceTableHandle<'ctx> {
    type UpdateCallbackId = UserPresenceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserPresenceUpdateCallbackId {
        UserPresenceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserPresenceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UserPresence>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserPresence>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `user_identity` unique index on the table `user_presence`,
/// which allows point queries on the field of the same name
/// via the [`UserPresenceUserIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_presence().user_identity().find(...)`.
pub struct UserPresenceUserIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserPresence, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserPresenceTableHandle<'ctx> {
    /// Get a handle on the `user_identity` unique index on the table `user_presence`.
    pub fn user_identity(&self) -> UserPresenceUserIdentityUnique<'ctx> {
        UserPresenceUserIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("user_identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserPresenceUserIdentityUnique<'ctx> {
    /// Find the subscribed row whose `user_identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<UserPresence> {
        self.imp.find(col_val)
    }
}
