// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_selection_type::UserSelection;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_selection`.
///
/// Obtain a handle from the [`UserSelectionTableAccess::user_selection`] method on [`super::RemoteTables`],
/// like `ctx.db.user_selection()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_selection().on_insert(...)`.
pub struct UserSelectionTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserSelection>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_selection`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserSelectionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserSelectionTableHandle`], which mediates access to the table `user_selection`.
    fn user_selection(&self) -> UserSelectionTableHandle<'_>;
}

impl UserSelectionTableAccess for super::RemoteTables {
    fn user_selection(&self) -> UserSelectionTableHandle<'_> {
        UserSelectionTableHandle {
            imp: self.imp.get_table::<UserSelection>("user_selection"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserSelectionInsertCallbackId(__sdk::CallbackId);
pub struct UserSelectionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserSelectionTableHandle<'ctx> {
    type Row = UserSelection;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserSelection> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserSelectionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserSelectionInsertCallbackId {
        UserSelectionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserSelectionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserSelectionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserSelectionDeleteCallbackId {
        UserSelectionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserSelectionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserSelection>("user_selection");
    _table.add_unique_constraint::<__sdk::Identity>("user_identity", |row| &row.user_identity);
}
pub struct UserSelectionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserSelectionTableHandle<'ctx> {
    type UpdateCallbackId = UserSelectionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserSelectionUpdateCallbackId {
        UserSelectionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserSelectionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UserSelection>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserSelection>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `user_identity` unique index on the table `user_selection`,
/// which allows point queries on the field of the same name
/// via the [`UserSelectionUserIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_selection().user_identity().find(...)`.
pub struct UserSelectionUserIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserSelection, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserSelectionTableHandle<'ctx> {
    /// Get a handle on the `user_identity` unique index on the table `user_selection`.
    pub fn user_identity(&self) -> UserSelectionUserIdentityUnique<'ctx> {
        UserSelectionUserIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("user_identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserSelectionUserIdentityUnique<'ctx> {
    /// Find the subscribed row whose `user_identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<UserSelection> {
        self.imp.find(col_val)
    }
}
