// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserPresence {
    pub user_identity: __sdk::Identity,
    pub workflow_id: String,
    pub nickname: String,
    pub cursor_color: u32,
    pub cursor_x: f32,
    pub cursor_y: f32,
    pub last_seen: __sdk::Timestamp,
}

impl __sdk::InModule for UserPresence {
    type Module = super::RemoteModule;
}
