// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::workflow_edge_type::WorkflowEdge;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `workflow_edge`.
///
/// Obtain a handle from the [`WorkflowEdgeTableAccess::workflow_edge`] method on [`super::RemoteTables`],
/// like `ctx.db.workflow_edge()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.workflow_edge().on_insert(...)`.
pub struct WorkflowEdgeTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorkflowEdge>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `workflow_edge`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorkflowEdgeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorkflowEdgeTableHandle`], which mediates access to the table `workflow_edge`.
    fn workflow_edge(&self) -> WorkflowEdgeTableHandle<'_>;
}

impl WorkflowEdgeTableAccess for super::RemoteTables {
    fn workflow_edge(&self) -> WorkflowEdgeTableHandle<'_> {
        WorkflowEdgeTableHandle {
            imp: self.imp.get_table::<WorkflowEdge>("workflow_edge"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorkflowEdgeInsertCallbackId(__sdk::CallbackId);
pub struct WorkflowEdgeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorkflowEdgeTableHandle<'ctx> {
    type Row = WorkflowEdge;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorkflowEdge> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorkflowEdgeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorkflowEdgeInsertCallbackId {
        WorkflowEdgeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorkflowEdgeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorkflowEdgeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorkflowEdgeDeleteCallbackId {
        WorkflowEdgeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorkflowEdgeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorkflowEdge>("workflow_edge");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct WorkflowEdgeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorkflowEdgeTableHandle<'ctx> {
    type UpdateCallbackId = WorkflowEdgeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorkflowEdgeUpdateCallbackId {
        WorkflowEdgeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorkflowEdgeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<WorkflowEdge>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorkflowEdge>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `workflow_edge`,
/// which allows point queries on the field of the same name
/// via the [`WorkflowEdgeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.workflow_edge().id().find(...)`.
pub struct WorkflowEdgeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorkflowEdge, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorkflowEdgeTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `workflow_edge`.
    pub fn id(&self) -> WorkflowEdgeIdUnique<'ctx> {
        WorkflowEdgeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorkflowEdgeIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WorkflowEdge> {
        self.imp.find(col_val)
    }
}
