// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorkflowNode {
    pub id: u64,
    pub workflow_id: String,
    pub node_uuid: String,
    pub node_type: String,
    pub name: String,
    pub position_x: f32,
    pub position_y: f32,
    pub config_json: String,
    pub disabled: bool,
    pub last_modified_by: __sdk::Identity,
    pub last_modified_at: __sdk::Timestamp,
}


impl __sdk::InModule for WorkflowNode {
    type Module = super::RemoteModule;
}

