// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorkflowEdge {
    pub id: u64,
    pub workflow_id: String,
    pub from_node_uuid: String,
    pub from_output: String,
    pub to_node_uuid: String,
    pub to_input: String,
}


impl __sdk::InModule for WorkflowEdge {
    type Module = super::RemoteModule;
}

