// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::workflow_type::Workflow;

/// Table handle for the table `workflow`.
///
/// Obtain a handle from the [`WorkflowTableAccess::workflow`] method on [`super::RemoteTables`],
/// like `ctx.db.workflow()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.workflow().on_insert(...)`.
pub struct WorkflowTableHandle<'ctx> {
    imp: __sdk::TableHandle<Workflow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `workflow`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorkflowTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorkflowTableHandle`], which mediates access to the table `workflow`.
    fn workflow(&self) -> WorkflowTableHandle<'_>;
}

impl WorkflowTableAccess for super::RemoteTables {
    fn workflow(&self) -> WorkflowTableHandle<'_> {
        WorkflowTableHandle {
            imp: self.imp.get_table::<Workflow>("workflow"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorkflowInsertCallbackId(__sdk::CallbackId);
pub struct WorkflowDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorkflowTableHandle<'ctx> {
    type Row = Workflow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Workflow> + '_ { self.imp.iter() }

    type InsertCallbackId = WorkflowInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorkflowInsertCallbackId {
        WorkflowInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorkflowInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorkflowDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorkflowDeleteCallbackId {
        WorkflowDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorkflowDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

        let _table = client_cache.get_or_make_table::<Workflow>("workflow");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}
pub struct WorkflowUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorkflowTableHandle<'ctx> {
    type UpdateCallbackId = WorkflowUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorkflowUpdateCallbackId {
        WorkflowUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorkflowUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}


#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Workflow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Workflow>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        /// Access to the `id` unique index on the table `workflow`,
        /// which allows point queries on the field of the same name
        /// via the [`WorkflowIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.workflow().id().find(...)`.
        pub struct WorkflowIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Workflow, String>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> WorkflowTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `workflow`.
            pub fn id(&self) -> WorkflowIdUnique<'ctx> {
                WorkflowIdUnique {
                    imp: self.imp.get_unique_constraint::<String>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> WorkflowIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &String) -> Option<Workflow> {
                self.imp.find(col_val)
            }
        }
        