// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::workflow_node_type::WorkflowNode;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `workflow_node`.
///
/// Obtain a handle from the [`WorkflowNodeTableAccess::workflow_node`] method on [`super::RemoteTables`],
/// like `ctx.db.workflow_node()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.workflow_node().on_insert(...)`.
pub struct WorkflowNodeTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorkflowNode>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `workflow_node`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorkflowNodeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorkflowNodeTableHandle`], which mediates access to the table `workflow_node`.
    fn workflow_node(&self) -> WorkflowNodeTableHandle<'_>;
}

impl WorkflowNodeTableAccess for super::RemoteTables {
    fn workflow_node(&self) -> WorkflowNodeTableHandle<'_> {
        WorkflowNodeTableHandle {
            imp: self.imp.get_table::<WorkflowNode>("workflow_node"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorkflowNodeInsertCallbackId(__sdk::CallbackId);
pub struct WorkflowNodeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorkflowNodeTableHandle<'ctx> {
    type Row = WorkflowNode;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorkflowNode> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorkflowNodeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorkflowNodeInsertCallbackId {
        WorkflowNodeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorkflowNodeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorkflowNodeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorkflowNodeDeleteCallbackId {
        WorkflowNodeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorkflowNodeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorkflowNode>("workflow_node");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct WorkflowNodeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorkflowNodeTableHandle<'ctx> {
    type UpdateCallbackId = WorkflowNodeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorkflowNodeUpdateCallbackId {
        WorkflowNodeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorkflowNodeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<WorkflowNode>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorkflowNode>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `workflow_node`,
/// which allows point queries on the field of the same name
/// via the [`WorkflowNodeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.workflow_node().id().find(...)`.
pub struct WorkflowNodeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorkflowNode, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorkflowNodeTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `workflow_node`.
    pub fn id(&self) -> WorkflowNodeIdUnique<'ctx> {
        WorkflowNodeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorkflowNodeIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WorkflowNode> {
        self.imp.find(col_val)
    }
}
